export const Specialities = [
  "Allergy and Immunology",
  "Colorectal Surgery",
  "Dermatology",
  "Emergency Medicine",
  "Endocrinology",
  "General Surgery",
  "Geriatrics",
  "Hematology",
  "Hospital Medicine",
  "Immunology",
  "Medical Genetics",
  "Neurology",
  "Neurosurgery",
  "Nuclear Medicine",
  "Occupational Medicine",
  "Orthopedics",
  "Pediatric Surgery",
  "Pediatrics",
  "Physical Therapy",
  "Podiatry",
  "Preventive Healthcare",
  "Radiology",
  "Reconstructive Surgery",
  "Rheumatology",
  "Sports Medicine",
  "Surgery",
  "Urology",
  "Vascular Surgery",
];
