export const Specialities = [
  "Surgery",
  "Dermatology",
  "Physical Therapy",
  "General Surgery",
  "Pediatrics",
  "Emergency Medicine",
  "Neurology",
  "Urology",
  "Immunology",
  "preventive Healthcare",
  "Orthopedics",
  "Nuclear Medicine",
  "Medical Genetics",
  "Radiology",
  "Neurosurgery",
  "Hematology",
  "Hospital Medicine",
  "Vascular Surgery",
  "Colorectal Surgery",
  "Pediatric Surgery",
  "Occupational Medicine",
  "Podiatry",
  "Allergy and Immunology",
  "Sports Medicine",
  "Reconstructive Surgery",
  "Endocrinology",
  "Rheumatology",
  "Geriatrics",
];
