apiVersion: v1
kind: Service
metadata:
  name: mydocctorfrontend-service
spec:
  selector:
    app: mydocctorfrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: ClusterIP